name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: shaktipriya13
          entry_point: src/main.py
          args: --output dist/github-contribution-grid-snake.svg

      - name: Commit the animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
